#!/bin/sh
path=$(pwd)

echo "keyserver keyserver.ubuntu.com" >> ~/.gnupg/gpg.conf

sudo pacman -S neovim base-devel github-cli
yay -S nerd-fonts-ubuntu-mono slack-desktop discord spotify vscodium-bin lf-bin

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Home directory
ln -sf $PWD/wallpapers $HOME/wallpapers
ln -sf $PWD/.fehbg $HOME/.fehbg
ln -sf $PWD/.gitconfig $HOME/.gitconfig
ln -sf $PWD/.profile $HOME/.profile
ln -sf $PWD/.zshrc $HOME/.zshrc
ln -sf $PWD/.tmux.conf $HOME/.tmux.conf

# Config directory
[ ! -d $HOME/.config ] && mkdir $HOME/.config

[ ! -d $HOME/.config/VSCodium ] && mkdir -p $HOME/.config/VSCodium/User
[ ! -d $HOME/.config/VSCodium/User ] && mkdir $HOME/.config/VSCodium/User
ln -sf $path/config/VSCodium/keybindings.json $HOME/.config/VSCodium/User/keybindings.json
ln -sf $path/config/VSCodium/settings.json $HOME/.config/VSCodium/User/settings.json
ln -sf $path/config/VSCodium/keybindings.json $HOME/.config/Code\ -\ OSS/User/keybindings.json
ln -sf $path/config/VSCodium/settings.json $HOME/.config/Code\ -\ OSS/User/settings.json

[ -d $HOME/.config/alacritty ] && rm -rf $HOME/.config/alacritty
ln -sf $path/config/alacritty $HOME/.config/alacritty


[ -d $HOME/.config/bspwm ] && rm -rf $HOME/.config/bspwm
ln -sf $path/config/bspwm $HOME/.config/bspwm

[ -d $HOME/.config/lf ] && rm -rf $HOME/.config/lf
ln -sf $path/config/lf $HOME/.config/lf

[ -d $HOME/.config/neofetch ] && rm -rf $HOME/.config/neofetch
ln -sf $path/config/neofetch $HOME/.config/neofetch

[ -d $HOME/.config/nvim ] && rm -rf $HOME/.config/nvim
ln -sf $path/config/nvim $HOME/.config/nvim

[ -d $HOME/.config/polybar ] && rm -rf $HOME/.config/polybar
ln -sf $path/config/polybar $HOME/.config/polybar

[ -d $HOME/.config/sxhkd ] && rm -rf $HOME/.config/sxhkd
ln -sf $path/config/sxhkd $HOME/.config/sxhkd

[ -d $HOME/.config/tridactyl ] && rm -rf $HOME/.config/tridactyl
ln -sf $path/config/tridactyl $HOME/.config/tridactyl

[ -d $HOME/.config/zathura ] && rm -rf $HOME/.config/zathura
ln -sf $path/config/zathura $HOME/.config/zathura

ln -sf $path/config/mimeapps.list $HOME/.config/mimeapps.list
